In [2]:
import numpy as np
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
import torch
#标量
x = torch.tensor(3.0)
y = torch.tensor(4.0)
x+y , x*y , x/y , x**y

(tensor(7.), tensor(12.), tensor(0.7500), tensor(81.))

In [4]:
#向量
x = torch.arange(5)
print(x)
x[3],x[4],x[-1]

tensor([0, 1, 2, 3, 4])


(tensor(3), tensor(4), tensor(4))

In [5]:
print(len(x))  #
x.shape        #列出每个轴的长度

5


torch.Size([5])

In [6]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
#对称矩阵
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [9]:
C = torch.arange(20,dtype=torch.float32).reshape(5,4)
D = C.clone()  #通过分配新内存，将A的一个副本分配给B
C , C+D

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [10]:
C * D

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [11]:
E = torch.arange(9).reshape(3,3)
F = torch.tensor([[1],[2],[3]])
E,F

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[1],
         [2],
         [3]]))

In [ ]:
print(E @ F)  
torch.mm(E,F)

tensor([[ 8],
        [26],
        [44]])


tensor([[ 8],
        [26],
        [44]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape
#降维（使用sum()函数
x = torch.arange(4,dtype=torch.float32)
x ,x.sum(), x.shape  

(tensor([0., 1., 2., 3.]), tensor(6.), torch.Size([4]))

In [14]:
A_sum_axis0 = A.sum(axis=0)  #矩阵沿0轴降维
A_sum_axis0 , A_sum_axis0.shape   

(tensor([40, 45, 50, 55]), torch.Size([4]))

In [15]:
A_sum_axis1 = A.sum(axis=1)  #矩阵沿1轴降维
A_sum_axis1 , A_sum_axis1.shape 

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

In [16]:
A.sum(axis=[0,1])

tensor(190)

In [17]:
A.mean(dtype=torch.float32), A.sum() / A.numel()
A.mean(axis=0, dtype=torch.float32), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [18]:
#非降维求和
sum_A = A.sum(axis=0,keepdims=True)
sum_A

tensor([[40, 45, 50, 55]])

In [19]:
A/sum_A

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [20]:
A.cumsum(axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

In [21]:

A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [22]:
#向量点积
y = torch.ones(4,dtype = torch.float32)
x , y , torch.dot (x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [23]:

#范数（表示一个向量有多大,优化问题
u = torch.tensor([3.0,-4.0])
torch.norm(u)   #L2范数，所有元素平方和的平方根

tensor(5.)

In [24]:

torch.abs(u).sum()  #L1范数

tensor(7.)

In [25]:

torch.norm(torch.ones((4,9)))  #L2范数

tensor(6.)